name = "tpNotes"
uuid = "f41428ba-fd88-40db-984c-5449a488a786"
authors = ["Thomas Poulsen"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
DocumenterTools = "0.1"
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
